<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>OverdoseChaos</AssemblyName>
    <Description>Un mod chaotique pour Lethal Company avec vagues de monstres et d'objets.</Description>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Références aux DLLs du jeu (place-les dans ton dossier libs) -->
    <Reference Include="Assembly-CSharp">
      <HintPath>libs\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>libs\Unity.Netcode.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>libs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>libs\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.ǎi, Version=5.4.21.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>libs\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>libs\0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
